### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by bilal333** [pgaskin/ePubViewer#1]
error loading cover: TypeError: url is undefined
{"error":"TypeError: url is undefined","stack":"getBlob@https://geek1011.github.io/ePubViewer/libs/epub.js:16017:8\ncreateUrl@https://geek1011.github.io/ePubViewer/libs/epub.js:16102:16\nApp.prototype.onBookCoverLoaded@https://geek1011.github.io/ePubViewer/script.js:326:5\nk/

**Comment by pgaskin** [comment]
This seems like a browser compatibility issue. Which browser are you using?

**Comment by bilal333** [comment]
Firefox

**Comment by pgaskin** [comment]
Version?

**Comment by pgaskin** [comment]
I'm going to close this issue, as there hasn't been any response.

**Comment by bilal333** [comment]
firefox 61.0.2 , Ubuntu 16.04
________________________________
