### ISSUE TITLE
Open Book Error

### ISSUE THREAD

**Issue by vdemir** [pgaskin/ePubViewer#13]
Steps:
1. Visit to link and look error.
https://kuranvebilim.github.io/viewer/ePubViewer/#https://kuranvebilim.github.io/assets/Harun_Yahya_Kitaplar/AA/epub/akilsizKuraniNasilYorumlar_11b_tr.epub

2. as Manual open file  at https://kuranvebilim.github.io/viewer/ePubViewer and no problem, normally opens epub file.

1. Manually it opens normal but if it visits to link what does not open.

Error
error loading book: Error: response status: 404
{"error":"Error: response status: 404 ","stack":"Error: response status: 404 \n at https://kuranvebilim.github.io/viewer/ePubViewer/script.js:678:43"}
[akilsizKuraniNasilYorumlar_11b_tr.zip](https://github.com/geek1011/ePubViewer/files/3716581/akilsizKuraniNasilYorumlar_11b_tr.zip)

Expected Result
1. It visits to link what opens.

**Comment by pgaskin** [comment]
I can't reproduce it. Try visiting the epub directly again, or clearing your cache.
