### ISSUE TITLE
Fonts size not change

### ISSUE THREAD

**Issue by vdemir** [pgaskin/ePubViewer#16]
The font size should able to change. No changes are seen in the application.
![Screenshot_20200628_143344](https://user-images.githubusercontent.com/7329803/85946384-ad0a2e00-b94c-11ea-8b96-d23383d9b2bc.png)

**Comment by pgaskin** [comment]
This tends to depend on the book, as some are too strict with their styles, and we don't want to overwrite things which are supposed to be smaller/larger.
