### ISSUE TITLE
guys, not work. fix the error. thanks.

### ISSUE THREAD

**Issue by Gabrielm3** [pgaskin/ePubViewer#25]
this is the error: `{"error":"TypeError: Unable to get property 'prev' of undefined or null reference","stack":"TypeError: Unable to get property 'prev' of undefined or null reference\n at App.prototype.onKeyUp (ms-appx-web://bluskysoftwareinc.ebooksreaderforkindlebooksmobiep/script.js:424:9)","msg":"Unable to get property 'prev' of undefined or null reference","url":"ms-appx-web://bluskysoftwareinc.ebooksreaderforkindlebooksmobiep/script.js","line":424,"column":9}`

**Comment by pgaskin** [comment]
This is not an issue with ePubViewer. Please contact the author of the application which embedded it instead (it appears to be https://www.microsoft.com/en-ca/p/ebooks-reader-for-kindle-books-mobi-epub-more/9ndgtn8cdqjb?activetab=pivot:overviewtab).
